# Generated by Django 3.1 on 2020-08-23 16:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Порода')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('family', models.CharField(choices=[('CAT', 'Кошка'), ('DOG', 'Собака'), ('PAR', 'Попугай')], default='CAT', max_length=3, verbose_name='Семейство')),
                ('sex', models.CharField(choices=[('M', 'Мальчик'), ('F', 'Девочка')], default='M', max_length=1, verbose_name='Пол')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата поступления')),
                ('photo', models.ImageField(blank=True, upload_to='pets_photo', verbose_name='Фото')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.breed', verbose_name='Порода')),
            ],
        ),
    ]
